chore: versions of dependent packages are centrally managed in longhorn/dep-versions
Longhorn 10208

Signed-off-by: Derek Su <derek.su@suse.com>
(cherry picked from commit 78c6e1d1c7371f43233e107863605b8f5c22c439)

diff --git a/scripts/package b/scripts/package
--- a/scripts/package
+++ b/scripts/package
@@ -13,16 +13,59 @@ fi
 
 cp -r bin package/
 
-APIVERSION=`./bin/longhorn-share-manager version --client-only|jq ".clientVersion.apiVersion"`
+arch=$(uname -m)
+if [ "$arch" == "aarch64" ]; then
+    ARCH="arm64"
+else
+    ARCH="amd64"
+fi
+APIVERSION=`./bin/longhorn-share-manager-"$ARCH" version --client-only|jq ".clientVersion.apiVersion"`
+
 TAG=${TAG:-"v${APIVERSION}_`date -u +%Y%m%d`"}
 REPO=${REPO:-longhornio}
 IMAGE=${REPO}/${PROJECT}:${TAG}
+
+function convert_version_to_major_minor_x() {
+    local version="$1"
+    if [[ "$version" =~ ^v([0-9]+)\.([0-9]+)\. ]]; then
+        echo "v${BASH_REMATCH[1]}.${BASH_REMATCH[2]}.x"
+    else
+        echo "Invalid version format: $version"
+    fi
+}
+
+function get_branch() {
+  local version_file="version"
+  if [[ ! -f $version_file ]]; then
+    echo "Error: Version file '$version_file' not found."
+    exit 1
+  fi
+
+  local version=$(cat "$version_file")
+  local branch=$(convert_version_to_major_minor_x "$version")
+
+  # Fetch versions.json from the appropriate branch, fallback to main
+  wget -q "https://raw.githubusercontent.com/longhorn/dep-versions/${branch}/versions.json" -O /versions.json
+  if [ $? -eq 0 ]; then
+    echo "${branch}"
+  else
+    echo "main"
+  fi
+}
+
+BRANCH=$(get_branch)
 
 # update base image to get latest changes
 BASE_IMAGE=`grep FROM package/Dockerfile | grep -v AS | awk '{print $2}'`
 docker pull ${BASE_IMAGE}
 
-buildx build --load -t ${IMAGE} -f package/Dockerfile .
+echo "Building image ${IMAGE} based on ${BASE_IMAGE}"
+buildx build \
+  --load \
+  --build-arg ARCH="${ARCH}" \
+  --build-arg BRANCH="${BRANCH}" \
+  -t "${IMAGE}" \
+  -f package/Dockerfile .
 
 echo Built ${IMAGE}
 
