ci: change to use GitHub actions
Signed-off-by: PoAn Yang <poan.yang@suse.com>

diff --git a/package/Dockerfile b/package/Dockerfile
--- a/package/Dockerfile
+++ b/package/Dockerfile
@@ -1,6 +1,6 @@
-FROM registry.suse.com/bci/bci-base:15.5 AS build
+# syntax=docker/dockerfile:1.7.1
 
-ARG ARCH=amd64
+FROM registry.suse.com/bci/bci-base:15.5 AS build
 
 # Based on https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner/blob/master/deploy/docker/x86_64/Dockerfile
 # Build ganesha from source, install it to /usr/local and a use multi stage build to have a smaller image
@@ -41,6 +41,13 @@ RUN mkdir -p /ganesha-extra \
 
 FROM registry.suse.com/bci/bci-base:15.5
 
+ARG TARGETPLATFORM
+RUN if [ "$TARGETPLATFORM" != "linux/amd64" ] && [ "$TARGETPLATFORM" != "linux/arm64" ]; then \
+    echo "Error: Unsupported TARGETPLATFORM: $TARGETPLATFORM" && \
+    exit 1; \
+    fi
+ENV ARCH ${TARGETPLATFORM#linux/}
+
 RUN zypper addrepo --refresh https://download.opensuse.org/repositories/system:/snappy/SLE_15/ snappy && \
     zypper --gpg-auto-import-keys ref
 
@@ -61,7 +68,7 @@ RUN ln -sf /proc/self/mounts /etc/mtab
 
 COPY --from=build /usr/local /usr/local/
 COPY --from=build /ganesha-extra /
-COPY bin/longhorn-share-manager /longhorn-share-manager
+COPY package/bin/longhorn-share-manager-${ARCH} /longhorn-share-manager
 
 # run ldconfig after libs have been copied
 RUN ldconfig
